build:
  variables:
    GIT_STRATEGY: clone
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
    GIT_SUBMODULE_STRATEGY: recursive
  image: xilinx:2024.1
  tags:
    - xilinx
  script:
    - source /opt/Xilinx/Vivado/2024.1/settings64.sh && cd fpga && scripts/build_fpga.sh && cd ..
    - source /home/xilinx/petalinux/2024.1/settings.sh && cd linux && scripts/build_image.sh devopsexample 
  artifacts:
    paths:
      - linux/**/images/linux/image.ub
      - linux/**/images/linux/BOOT.BIN
      - linux/**/images/linux/boot.scr
      - fpga/vivado/**/impl_1/*.bit

